name: Run tests

on:
  workflow_call:
    secrets:
      SAUCE_ACCESS_KEY:
        required: true

  pull_request:
    paths-ignore:
      - '.changeset/**'

  schedule:
    # run every day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  run-vitest:
    name: Run vitest tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm test

  run-karma:
    name: Run karma tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm build
      # - run: pnpm karma
      #   env:
      #     CI: true
      #     TZ: 'America/Los_Angeles'
      #     SAUCE_USERNAME: jsxstyle
      #     SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
