name: CI

on:
  push:
    paths-ignore:
      - '.changeset/**'

  pull_request:
    paths-ignore:
      - '.changeset/**'

  schedule:
    # run every day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout jsxstyle
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run jest
        run: yarn run test

      - name: Run karma
        run: yarn run karma
        env:
          CI: true
          TZ: 'America/Los_Angeles'
          SAUCE_USERNAME: jsxstyle
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
