name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'minisite/**'
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm install
      - run: npm run build
      - run: npm -w minisite run export

      - name: Fetch gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages-temp

      - name: Update gh-pages branch
        run: |
          export COMMIT_TITLE="$(git show --pretty=format:%s -s HEAD)"
          export GIT_COMMITTER_DATE="$(git show -s --format=%ci HEAD)"
          export GIT_AUTHOR_DATE="$(git show -s --format=%ai HEAD)"
          cd gh-pages-temp
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -rf .
          cp -r ../minisite/dist/. .
          git add -A
          git commit -m "$COMMIT_TITLE"
          git push origin HEAD
