name: Release

on:
  push:
    branches:
      - main

jobs:
  canary:
    name: Create and publish a new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout jsxstyle
        uses: actions/checkout@v2
        with:
          # fetch everything so that we can properly calculate what needs to be published
          fetch-depth: 0

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Run jest
        run: npm test

      - name: Run karma
        run: npm run karma
        env:
          CI: true
          TZ: 'America/Los_Angeles'
          SAUCE_USERNAME: jsxstyle
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      - name: Configure NPM
        run: |
          npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm set username ${{ secrets.NPM_USERNAME }}
          npm set email ${{ secrets.NPM_EMAIL }}

      - name: Create release PR or publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          commit: Bump versions
          title: Bump versions
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publishing canary release
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout main
          npm run version:canary
          npm run release:canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
